"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os
from environs import Env

env = Env()
env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(2sz2f@eob*q24i&rdu5qxxo_b_hfm6vhe1c5+(6!9rbx5pong'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['neotrip.uz', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://neotrip.uz',
]
CORS_ALLOWED_ORIGINS = [
    "https://neotrip.uz",
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_email_verification",
    'bootstrap4',
    "payme",
    "drf_yasg",
    "rest_framework",
    "user",
    "main",
    "post",
    "tour",
    'order',
    'ckeditor',
    'ckeditor_uploader',
    'easy_thumbnails',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Make sure this line is present
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "user.views.my_context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('fr', _('French')),
    ('en', _('English')),
    ('ru', _('Russian')),

)

MODELTRANSLATION_DEFAULT_LANGUAGE = ('fr' )
# MODELTRANSLATION_LANGUAGES = ('ru', 'uz')

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# URL for static files
STATIC_URL = '/static/'

# Directory where Django will collect static files for deployment
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional directories to search for static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL for media files
MEDIA_URL = '/media/'

# Directory where media files are uploaded
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = "uploads/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = 'user.User'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_PORT = 587
PASSWORD_RESET_TIMEOUT = 60 * 30

PAYME: dict = {
    'PAYME_ID': env.str("PAYME_ID"),
    'PAYME_KEY': env.str("PAYME_KEY"),
    'PAYME_URL': env.str("PAYME_URL"),
    'PAYME_CALL_BACK_URL': env.str("PAYME_CALL_BACK_URL"),
    'PAYME_MIN_AMOUNT': env.int("PAYME_MIN_AMOUNT", default=0),
    'PAYME_ACCOUNT': env.str("PAYME_ACCOUNT"),
}

ORDER_MODEL = 'order.models.Order'


JAZZMIN_SETTINGS = {
    "site_title": "Neo Trip",
    "site_header": "NeoTrip Admin",
    "site_brand": "Neo Trip",
    "welcome_sign": "Neo Trip boshqaruv paneliga xush kelibsiz!",
    "site_logo": "assets/img/favicons/apple-icon-57x57.png",  # Static papkada joylashgan logotip
    "login_logo": "assets/img/favicons/apple-icon-57x57.png",
    "login_logo_dark": "assets/img/favicons/apple-icon-57x57.png",
    "copyright": "Neo Trip",
    "search_model": "auth.User",  # Qidiruv oynasida modelni qidirish
    "user_avatar": None,          # Foydalanuvchi avatari (model bilan bog'lash mumkin)
    "topmenu_links": [            # Yuqoridagi menyu tugmalari
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "myapp"},
    ],
    "usermenu_links": [           # Foydalanuvchi menyusi uchun tugmalar
        {"name": "Support", "url": "https://support.example.com", "new_window": True},
    ],
    "show_sidebar": True,         # Yon panelni ko'rsatish yoki yashirish
    "navigation_expanded": True,  # Yon panel kengaytirilgan holda ochiladi
    "hide_apps": ["auth"],        # Ko'rinmas bo'lishi kerak bo'lgan ilovalar
    "hide_models": ["auth.User"], # Ko'rinmas bo'lishi kerak bo'lgan modellar
    "order_with_respect_to": ["auth", "myapp"],  # Ilovalar tartibi
}
